printf "# GNUstep Base Expiremental API Reference

This is an extremely experimental API reference for GNUstep Base, which is generated by ETDocGen and then included into a Sphinx document.

\`\`\`{toctree}
---
caption: Contents
titlesonly: true
---
" > index.md

for htmlFile in Base/*.html; do
    title=${htmlFile%%.html}
    title=${title##Base\/}
    printf "
# ${title}

Automatically generated from ${htmlFile}.

\`\`\` {raw} html
---
file: ${title}.html
---
\`\`\`
" > ${htmlFile%%.html}.md
    printf "
${htmlFile%%.html}.md" >> index.md
done

printf "
---
" >> index.md